version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "deps"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
