"""
minxg/chaos/ifs.py — Iterated Function Systems & Classic Fractals
========================================================================

An ITERATED FUNCTION SYSTEM (IFS) is a set of contraction maps
{w_1, w_2, ..., w_n} on a metric space. The unique attractor is the
set K satisfying K = ⋃_i w_i(K). Famous examples:

  - SIERPINSKI GASKET: 3 contractions
  - KOCH SNOWFLAKE:    4 contractions
  - DRAGON CURVE:      2 contractions
  - CANTOR SET:        2 contractions
  - BARNsLEY FERN:     4 affine contractions
  - HILBERT CURVE:     4 contractions

We provide both symbolic and numerical generation.
"""
from __future__ import annotations
import math
import random
from typing import Callable, List, Tuple


def iterated_function_system(contractions: List[Callable[[Tuple[float, ...]], Tuple[float, ...]]],
                              x0: Tuple[float, ...],
                              n_points: int = 10000) -> List[Tuple[float, ...]]:
    """Generate the attractor of an IFS via the chaos game.

    Pick a random contraction at each step; the iterates converge to the
    attractor almost surely.
    """
    pts = [x0]
    x = x0
    for _ in range(n_points):
        w = random.choice(contractions)
        x = w(x)
        pts.append(x)
    return pts


def sierpinski_gasket(n_points: int = 10000) -> List[Tuple[float, float]]:
    """The Sierpinski gasket — generated by 3 contractions with factor 1/2."""
    contractions = [
        lambda p: (p[0] / 2, p[1] / 2),                           
        lambda p: (p[0] / 2 + 0.5, p[1] / 2),                     
        lambda p: (p[0] / 2 + 0.25, p[1] / 2 + 0.5),              
    ]
    return iterated_function_system(contractions, (0.5, 0.5), n_points)


def koch_snowflake(n_points: int = 10000) -> List[Tuple[float, float]]:
    """The Koch snowflake — 4 contractions producing a self-similar curve."""
    
    contractions = [
        lambda p: (p[0] / 3, p[1] / 3),
        lambda p: (p[0] / 3 + 1 / 3, p[1] / 3),
        lambda p: (p[0] / 3 + 2 / 3, p[1] / 3),
        
        lambda p: (p[0] / 3 + 1 / 2 - p[1] / (2 * math.sqrt(3)),
                    p[1] / 3 + 1 / (2 * math.sqrt(3)) + p[0] / (2 * math.sqrt(3)) - 1 / 4),
    ]
    return iterated_function_system(contractions, (0.5, 0.3), n_points)


def dragon_curve(n_points: int = 10000) -> List[Tuple[float, float]]:
    """The Heighway dragon curve — 2 contractions."""
    contractions = [
        lambda p: ((p[0] * math.cos(math.pi / 4) - p[1] * math.sin(math.pi / 4)) / math.sqrt(2),
                    (p[0] * math.sin(math.pi / 4) + p[1] * math.cos(math.pi / 4)) / math.sqrt(2)),
        lambda p: (1 + (p[0] * math.cos(3 * math.pi / 4) - p[1] * math.sin(3 * math.pi / 4)) / math.sqrt(2),
                    (p[0] * math.sin(3 * math.pi / 4) + p[1] * math.cos(3 * math.pi / 4)) / math.sqrt(2)),
    ]
    return iterated_function_system(contractions, (0.5, 0.5), n_points)


def barnsley_fern(n_points: int = 10000) -> List[Tuple[float, float]]:
    """The Barnsley fern — 4 affine contractions with weighted probabilities."""
    
    contractions = [
        lambda p: (0, 0.16 * p[1]),  
        lambda p: (0.85 * p[0] + 0.04 * p[1], -0.04 * p[0] + 0.85 * p[1] + 1.6),
        lambda p: (0.2 * p[0] - 0.26 * p[1], 0.23 * p[0] + 0.22 * p[1] + 1.6),
        lambda p: (-0.15 * p[0] + 0.28 * p[1], 0.26 * p[0] + 0.24 * p[1] + 0.44),
    ]
    return iterated_function_system(contractions, (0.5, 0.5), n_points)


def cantor_set(n_points: int = 10000) -> List[Tuple[float, float]]:
    """The Cantor set — 2 contractions in 1D (rendered as y=0)."""
    contractions = [
        lambda p: (p[0] / 3, 0),
        lambda p: (p[0] / 3 + 2 / 3, 0),
    ]
    return iterated_function_system(contractions, (0.5, 0.0), n_points)
