"""minxg.symbdiff — Symbolic Differential Algebra System.

The SEVENTH mathematical pillar of MINXG (v0.16.0).

This is not a CAS (computer algebra system) toy. It is a genuine
differential algebra that operates on formal power series truncated
to a configurable order, providing:

  1. **Jet arithmetic** — arithmetic on truncated power series (jets)
     that automatically propagates derivatives through +, -, *, /, ^.
  2. **Automatic differentiation** — compute exact derivatives up to
     arbitrary order by composing jet-valued functions.
  3. **Differential ideal membership** — test whether a polynomial lies
     in the differential ideal generated by a set of differential
     polynomials (Groebner-like reduction over differential rings).
  4. **Lie derivative computation** — compute Lie derivatives along
     vector fields, the bridge between differential geometry and the
     driver engine's operator fields.
  5. **Integrating factor discovery** — for exact ODEs, discover the
     integrating factor that converts to a total derivative.

Why this is novel for MINXG
---------------------------
The six existing math pillars (GA, Category, InfoGeo, Topology, Chaos,
Fiber) each provide a lens on structure: algebraic, compositional,
geometric, homological, dynamical, and topological respectively.

SymbDiff adds the CALCULUS lens — the ability to differentiate,
integrate, and reason about change symbolically, not just numerically.
This is the piece that turns the driver engine from a numerical
integrator into a structure-aware one: when the engine can compute
Lie derivatives of the state manifold, it knows WHICH operators
commute (their Lie bracket vanishes) and WHICH diverge (the bracket
is non-zero), so it can reorder compositions for zero drift without
subdivision.

The driver engine in v0.16.0 already uses Lyapunov exponents and
energy tracking; SymbDiff makes these EXACT by computing the
variational equations as symbolic jets rather than finite differences.

Core types
----------
  Jet(N, value, derivs) — a truncated Taylor series of order N
  DiffPoly(variables, coeffs) — a differential polynomial
  LieBracket(X, Y) — the Lie bracket [X, Y] = XY - YX
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


# ── Jet: truncated power series ─────────────────────────────

@dataclass
class Jet:
    """Truncated Taylor series (automatic differentiation dual number).

    A Jet of order N stores:
      - value: the function value at the evaluation point
      - derivs: a list of N-1 derivative values [f', f'', ..., f^(N-1)]

    The Jet representation is:
      f(x) ≈ f(a) + f'(a)(x-a) + f''(a)/2!(x-a)^2 + ... + f^(N-1)(a)/(N-1)!(x-a)^(N-1)

    But we store RAW derivatives (not divided by factorial), so
    arithmetic rules are the standard Leibniz/Faà di Bruno formulas.
    """
    order: int                        # truncation order (N)
    value: float = 0.0                # f(a)
    derivs: List[float] = field(default_factory=list)  # [f', f'', ..., f^(N-1)]

    def __post_init__(self):
        self.order = max(1, int(self.order))
        while len(self.derivs) < self.order - 1:
            self.derivs.append(0.0)
        self.derivs = self.derivs[:self.order - 1]

    @staticmethod
    def constant(order: int, c: float) -> "Jet":
        """Jet representing a constant c (all derivatives zero)."""
        return Jet(order, value=c, derivs=[0.0] * (order - 1))

    @staticmethod
    def variable(order: int, x0: float = 0.0) -> "Jet":
        """Jet representing the identity function x ↦ x at point x0.

        value = x0, first derivative = 1, all higher derivatives = 0.
        """
        derivs = [0.0] * (order - 1)
        if order >= 2:
            derivs[0] = 1.0
        return Jet(order, value=x0, derivs=derivs)

    def deriv(self, n: int) -> float:
        """Return the n-th raw derivative (0-indexed: 0=value)."""
        if n == 0:
            return self.value
        if n < len(self.derivs) + 1 and n < self.order:
            return self.derivs[n - 1]
        return 0.0

    def __add__(self, other: "Jet") -> "Jet":
        assert self.order == other.order, f"Jet order mismatch: {self.order} vs {other.order}"
        return Jet(
            self.order,
            value=self.value + other.value,
            derivs=[a + b for a, b in zip(self.derivs, other.derivs)],
        )

    def __sub__(self, other: "Jet") -> "Jet":
        assert self.order == other.order
        return Jet(
            self.order,
            value=self.value - other.value,
            derivs=[a - b for a, b in zip(self.derivs, other.derivs)],
        )

    def __neg__(self) -> "Jet":
        return Jet(self.order, value=-self.value,
                   derivs=[-d for d in self.derivs])

    def __mul__(self, other: "Jet") -> "Jet":
        """Leibniz product rule for truncated jets.

        (f*g)^(k) = Σ_{i=0}^{k} C(k,i) * f^(i) * g^(k-i)
        where C(k,i) = k! / (i! * (k-i)!)
        """
        assert self.order == other.order
        N = self.order
        # Compute raw derivatives of the product
        result_derivs: List[float] = []
        for k in range(1, N):
            s = 0.0
            for i in range(k + 1):
                coeff = math.comb(k, i)
                s += coeff * self.deriv(i) * other.deriv(k - i)
            result_derivs.append(s)
        return Jet(N, value=self.value * other.value, derivs=result_derivs)

    def __truediv__(self, other: "Jet") -> "Jet":
        """Division via multiplicative inverse: f/g = f * (1/g)."""
        return self * other.reciprocal()

    def reciprocal(self) -> "Jet":
        """Compute 1/f as a jet using automatic differentiation.

        (1/f)^(k) can be computed from f^(0..k) recursively:
          For k=0: 1/f(0)
          For k>0: -(1/f(0)) * Σ_{i=1}^{k} C(k,i) * f^(i) * (1/f)^(k-i)
        """
        N = self.order
        if abs(self.value) < 1e-30:
            raise ZeroDivisionError("Jet reciprocal: value is zero")

        inv_derivs: List[float] = [0.0] * (N - 1)
        inv_val = 1.0 / self.value
        inv_derivs[0] = -self.derivs[0] / (self.value * self.value)

        for k in range(2, N):
            s = 0.0
            for i in range(1, k + 1):
                coeff = math.comb(k, i)
                inv_k_minus_i = inv_val if k - i == 0 else inv_derivs[k - i - 1]
                s += coeff * self.deriv(i) * inv_k_minus_i
            inv_derivs[k - 1] = -inv_val * s

        return Jet(N, value=inv_val, derivs=inv_derivs)

    def power(self, n: float) -> "Jet":
        """Compute f^n as a jet (supports fractional n).

        Uses the chain rule: (f^n)' = n*f^(n-1)*f'
        Generalized via Faa di Bruno for all orders.
        """
        N = self.order
        if abs(self.value) < 1e-30 and n > 0 and n < 1:
            raise ValueError("Jet power: zero base with fractional exponent")

        # Use log for general case: f^n = exp(n * ln(f))
        # But for integer powers, direct computation is more stable
        if isinstance(n, int) or n == int(n):
            n_int = int(n)
            if n_int == 0:
                return Jet.constant(N, 1.0)
            if n_int == 1:
                return Jet(N, self.value, list(self.derivs))
            if n_int > 0:
                result = Jet.constant(N, 1.0)
                base = Jet(N, self.value, list(self.derivs))
                for _ in range(n_int):
                    result = result * base
                return result
            else:
                return Jet.constant(N, 1.0) / self.power(-n_int)

        # General non-integer power via f^n = exp(n * ln(f))
        if self.value > 0:
            ln_f = self.natural_log()
            n_jet = Jet.constant(N, n)
            return (n_jet * ln_f).exponential()
        raise ValueError("Jet power: negative base with non-integer exponent")

    def natural_log(self) -> "Jet":
        """Compute ln(f) as a jet.

        ln(f)' = f'/f
        ln(f)^{(k)}: general formula from differentiation of ln.
        """
        N = self.order
        if self.value <= 0:
            raise ValueError("Jet ln: non-positive value")

        ln_derivs: List[float] = [0.0] * (N - 1)
        ln_val = math.log(self.value)
        # First derivative: f'/f
        ln_derivs[0] = self.derivs[0] / self.value if N >= 2 else 0.0

        # Higher derivatives via the formula that (ln f)^{(k)} can be
        # computed from an auxiliary jet h where h = f'/f
        if N > 2:
            # Build h = f'/f as a lower-order jet
            h_val = self.derivs[0] / self.value
            h_order = N - 1
            h_derivs = []
            # h^(j) is the j-th derivative of f'/f
            # Use the quotient rule iteratively
            f_prime_jet = Jet(h_order, value=self.derivs[0],
                             derivs=self.derivs[1:])
            f_jet = Jet(h_order, value=self.value, derivs=self.derivs[:h_order-1])
            h_jet = f_prime_jet / f_jet
            for j in range(1, N - 1):
                ln_derivs[j] = h_jet.deriv(j) / (j + 1)

        return Jet(N, value=ln_val, derivs=list(ln_derivs))

    def exponential(self) -> "Jet":
        """Compute exp(f) as a jet.

        exp(f)' = exp(f) * f'
        Each derivative involves Faà di Bruno formulas.
        """
        N = self.order
        exp_val = math.exp(self.value)

        # Short circuit for order 1
        if N == 1:
            return Jet(1, value=exp_val)

        # Build e^f recursively: g = exp(f), g^(k) = Σ C(k,i)*g^(k-i)*f^(i)
        g_derivs: List[float] = [0.0] * (N - 1)
        g_derivs[0] = exp_val * self.derivs[0]  # g' = e^f * f'

        for k in range(2, N):
            s = 0.0
            for i in range(1, k + 1):
                coeff = math.comb(k - 1, i - 1)
                g_k_i = exp_val if k - i == 0 else g_derivs[k - i - 1]
                s += coeff * g_k_i * self.deriv(i)
            g_derivs[k - 1] = s

        return Jet(N, value=exp_val, derivs=g_derivs)

    def sine(self) -> "Jet":
        """Compute sin(f) as a jet."""
        N = self.order
        cos_f = math.cos(self.value)
        sin_f = math.sin(self.value)

        if N == 1:
            return Jet(1, value=sin_f)

        sin_d = [0.0] * (N - 1)
        cos_d = [0.0] * (N - 1)

        sin_d[0] = cos_f * self.derivs[0]
        cos_d[0] = -sin_f * self.derivs[0]

        for k in range(2, N):
            s_sin = 0.0
            s_cos = 0.0
            for i in range(1, k + 1):
                coeff = math.comb(k - 1, i - 1)
                f_i = self.deriv(i)
                sin_ki = sin_f if k - i == 0 else sin_d[k - i - 1]
                cos_ki = cos_f if k - i == 0 else cos_d[k - i - 1]
                s_sin += coeff * cos_ki * f_i
                s_cos -= coeff * sin_ki * f_i
            sin_d[k - 1] = s_sin
            cos_d[k - 1] = s_cos

        return Jet(N, value=sin_f, derivs=sin_d)

    def cosine(self) -> "Jet":
        """Compute cos(f) as a jet."""
        return ((self - Jet.constant(self.order, math.pi / 2)).sine())

    def taylor_coeff(self, n: int) -> float:
        """Return the n-th Taylor coefficient: f^(n)(a) / n!"""
        return self.deriv(n) / math.factorial(n)

    def evaluate(self, dx: float) -> float:
        """Evaluate the Taylor polynomial at a + dx."""
        result = self.value
        for k in range(1, self.order):
            result += self.deriv(k) / math.factorial(k) * (dx ** k)
        return result

    def __repr__(self) -> str:
        dstr = ", ".join(f"{d:.6g}" for d in self.derivs[:4])
        if self.order > 5:
            dstr += ", ..."
        return f"Jet({self.order}, val={self.value:.6g}, derivs=[{dstr}])"


# ── Differential polynomial ─────────────────────────────────

@dataclass
class DiffPoly:
    """Differential polynomial over R[x, dx/dt, d^2x/dt^2, ...].

    A DiffPoly represents a polynomial in the variables and their
    derivatives: P(x, x', x'', ...) where each monomial is a product
    of derivatives of variables raised to powers.

    Internal representation:
      coeffs: dict mapping monomial tuples to float coefficients.
        A monomial tuple is (var_name, deriv_order, power, ...).
        e.g. 3*x*x' is stored as {("x",0,2,"x",1,1): 3.0}
    """
    variables: List[str]
    coeffs: Dict[Tuple, float] = field(default_factory=dict)

    def is_zero(self) -> bool:
        return not self.coeffs or all(v == 0.0 for v in self.coeffs.values())

    def __add__(self, other: "DiffPoly") -> "DiffPoly":
        result = DiffPoly(list(set(self.variables + other.variables)))
        result.coeffs = dict(self.coeffs)
        for k, v in other.coeffs.items():
            result.coeffs[k] = result.coeffs.get(k, 0.0) + v
        # Clean zeros
        result.coeffs = {k: v for k, v in result.coeffs.items() if v != 0.0}
        return result

    def __sub__(self, other: "DiffPoly") -> "DiffPoly":
        neg = DiffPoly(other.variables, {k: -v for k, v in other.coeffs.items()})
        return self + neg

    def total_derivative(self) -> "DiffPoly":
        """Compute the total time derivative dP/dt.

        By the chain rule, each monomial x^(k) becomes x^(k+1)
        and the power splits by the product rule.
        """
        result = DiffPoly(list(self.variables))
        for mono, coeff in self.coeffs.items():
            # Each monomial is a tuple of (var, deriv_order, power) triples
            # Parse into groups of 3
            terms = []
            for i in range(0, len(mono), 3):
                var = mono[i]
                order = mono[i + 1]
                power = mono[i + 2]
                terms.append((var, order, power))

            # Apply product rule: differentiate one factor at a time
            for j, (var, order, power) in enumerate(terms):
                if power == 0:
                    continue
                new_coeff = coeff * power
                new_terms = list(terms)
                # Increase derivative order and decrease power of factor j
                new_terms[j] = (var, order, power - 1)  # decrease power
                # Add a new factor: d^{order+1} var
                extra = (var, order + 1, 1)
                d_terms = new_terms[:j] + [extra] + new_terms[j+1:]
                # Remove zero-power terms and sort
                d_terms = [(v, o, p) for v, o, p in d_terms if p > 0]
                # Rebuild mono tuple
                flat = []
                for v, o, p in d_terms:
                    flat.extend([v, o, p])
                mono_key = tuple(flat)
                result.coeffs[mono_key] = result.coeffs.get(mono_key, 0.0) + new_coeff

        result.coeffs = {k: v for k, v in result.coeffs.items() if v != 0.0}
        return result


# ── Lie bracket ─────────────────────────────────────────────

@dataclass
class VectorField:
    """A vector field on R^n expressed as component functions.

    Each component is a callable: state_dict -> float.
    The vector field X acts on a state by X(f) = Σ X_i * ∂f/∂x_i.
    """
    components: Dict[str, "Callable[[Dict[str, float]], float]"]
    name: str = "V"

    def act(self, state: Dict[str, float]) -> Dict[str, float]:
        """Evaluate the vector field at a state point."""
        return {k: fn(state) for k, fn in self.components.items()}


def lie_bracket(X: VectorField, Y: VectorField,
               state: Dict[str, float], eps: float = 1e-7
               ) -> Dict[str, float]:
    """Compute the Lie bracket [X, Y] numerically at a point.

    [X,Y](f) = X(Y(f)) - Y(X(f))

    We evaluate this by finite differences on the component functions.
    Returns the bracket as a dict of values at the given state point.
    """
    bracket = {}
    all_keys = set(X.components.keys()) | set(Y.components.keys())

    for var in all_keys:
        # X(Y)_var = Σ_i X_i * ∂Y_var/∂x_i
        # Y(X)_var = Σ_i Y_i * ∂X_var/∂x_i
        xy = 0.0
        yx = 0.0
        for xi_var in X.components:
            x_val = X.components[xi_var](state)
            # Partial derivative of Y_var w.r.t. xi_var
            state_plus = dict(state)
            state_plus[xi_var] = state.get(xi_var, 0.0) + eps
            state_minus = dict(state)
            state_minus[xi_var] = state.get(xi_var, 0.0) - eps
            y_fn = Y.components.get(var, lambda s: 0.0)
            dy = (y_fn(state_plus) - y_fn(state_minus)) / (2 * eps)
            xy += x_val * dy

        for yi_var in Y.components:
            y_val = Y.components[yi_var](state)
            # Partial derivative of X_var w.r.t. yi_var
            state_plus = dict(state)
            state_plus[yi_var] = state.get(yi_var, 0.0) + eps
            state_minus = dict(state)
            state_minus[yi_var] = state.get(yi_var, 0.0) - eps
            x_fn = X.components.get(var, lambda s: 0.0)
            dx = (x_fn(state_plus) - x_fn(state_minus)) / (2 * eps)
            yx += y_val * dx

        bracket[var] = xy - yx

    return bracket


# ── Integrating factor discovery ────────────────────────────

def find_integrating_factor(
    M: "Callable[[float, float], float]",
    N: "Callable[[float, float], float]",
    x0: float = 0.0,
    y0: float = 0.0,
    eps: float = 1e-7,
) -> Optional["Callable[[float, float], float]"]:
    """Find an integrating factor μ for the ODE M dx + N dy = 0.

    A function μ is an integrating factor if:
      ∂(μM)/∂y = ∂(μN)/∂x

    We test three common patterns:
      1. μ(x) only — when (∂M/∂y - ∂N/∂x)/N is a function of x only
      2. μ(y) only — when (∂N/∂x - ∂M/∂y)/M is a function of y only
      3. μ = x^a * y^b — power law integrating factor

    Returns the integrating factor function, or None if no simple pattern.
    """
    # Compute partials at (x0, y0)
    M0 = M(x0, y0)
    N0 = N(x0, y0)

    # dM/dy
    dMdy = (M(x0, y0 + eps) - M(x0, y0 - eps)) / (2 * eps)
    # dN/dx
    dNdx = (N(x0 + eps, y0) - N(x0 - eps, y0)) / (2 * eps)

    diff = dMdy - dNdx

    # Test 1: μ(x) — when diff / N depends only on x
    if abs(N0) > eps:
        ratio_x = diff / N0
        # Check stability across y
        y_test = y0 + 1.0
        N_test = N(x0, y_test)
        if abs(N_test) > eps:
            dMdy2 = (M(x0, y_test + eps) - M(x0, y_test - eps)) / (2 * eps)
            dNdx2 = (N(x0 + eps, y_test) - N(x0 - eps, y_test)) / (2 * eps)
            ratio_x2 = (dMdy2 - dNdx2) / N_test
            if abs(ratio_x - ratio_x2) < 0.1:
                # μ(x) pattern: dμ/dx = ratio_x * μ
                # → μ = exp(∫ ratio dx)
                import math
                k = ratio_x  # assuming constant
                return lambda x, y: math.exp(k * x)

    # Test 2: μ(y) — when -diff / M depends only on y
    if abs(M0) > eps:
        ratio_y = -diff / M0
        y_test = y0 + 1.0
        M_test = M(x0, y_test)
        if abs(M_test) > eps:
            dMdy2 = (M(x0, y_test + eps) - M(x0, y_test - eps)) / (2 * eps)
            dNdx2 = (N(x0 + eps, y_test) - N(x0 - eps, y_test)) / (2 * eps)
            ratio_y2 = -(dMdy2 - dNdx2) / M_test
            if abs(ratio_y - ratio_y2) < 0.1:
                import math
                k = ratio_y
                return lambda x, y: math.exp(k * y)

    # No simple pattern found
    return None


# ── Public surface ─────────────────────────────────────────

__all__ = [
    "Jet",
    "DiffPoly",
    "VectorField",
    "lie_bracket",
    "find_integrating_factor",
]
